Vagrant.configure(2) do |config|
  
  config.vm.box = "bento/ubuntu-14.04"
  config.vm.network "private_network", type: "dhcp"
  config.vm.provider :virtualbox do |vb|
    vb.memory = 1024
    vb.cpus = 1
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.vm.define "vagrant-docker-test" do |node_config|
    node_config.vm.hostname = "vagrant-docker-test"
  end
end